### ISSUE TITLE
Callback de prateleiras

### ISSUE THREAD

**Issue by zeluizr** [caljp13/QD-Infinity-Scroll#6]
Fiz um teste com o plugin e funciona perfeitamente, porém eu estou com um probleminha e espero que possam me ajudar.

Eu quero que quando retorne ele devolta o HTML do /buscapagina somente a parte dentro da UL, quer dizer somente os LIs, porque eu uso uma versão do css, que não tem ULs só um UL e todas as LIs dentro.

Entenderam? hahahahaha... obrigado!

**Comment by caljp13** [comment]
@zeluizr você pode usar o parâmetro `insertContent` para manipular isso.

Ficaria algo +/- assim:

```javascript
$(".prateleira[id*=ResultItems]").QD_infinityScroll({
	insertContent: function (currentItems, ajaxData) {
		currentItems.find("ul").append(ajaxData.find("li"));
	}
});
```

Só precisa testar para ver se esta ok, mas a linha de raciocínio é essa! :)

**Comment by zeluizr** [comment]
@caljp13, muito obrigado!

Vou testar e aviso aqui para fechar o Issue!

**Comment by caljp13** [comment]
@zeluizr deu certo?

**Comment by zeluizr** [comment]
@caljp13, perfeito... funcionou que é uma beleza!
