### ISSUE TITLE
Método paginate

### ISSUE THREAD

**Issue by guilhermemarconi** [caljp13/QD-Infinity-Scroll#7]
Dei uma olhada no método `paginate` da função mas não consegui entender bem seu funcionamento, pois como eu vou executar a função se ela faz parte do plugin? Eu teria que, a cada clique no botão que quero, fazer uma nova instância do plugin para retornar a página? Não ficou muito clara a explicação deste método.

> Ela recebe como parâmetro: 1 função que chama a próxima página (caso ela exista)

Estou trabalhando com LazyLoad e, com scroll, não está ficando legal. Pensei em tentar usar um botão desses para ver se dá uma melhorada.

**Comment by caljp13** [comment]
@guilhermemarconi segue abaixo um exemplo do uso da função `paginate`. No exemplo eu estou utilizando um botão "Ver mais resultados" para carregar a próxima página.

```
$(".prateleira[id*=ResultItems]").QD_infinityScroll({
	paginate: function(nextPage) {
		$(".carregar-proxima-pagina").click(function() {
			if(nextPage())
				$(this).slideUp();
			return false;
		});
	}
});
```

Isso te ajuda?

**Comment by guilhermemarconi** [comment]
@caljp13 ajuda muito! Na documentação não está muito intuitiva a forma de utilizar, mas agora ficou claro.

Obrigado!
