### ISSUE TITLE
Como manter o History da paginação?

### ISSUE THREAD

**Issue by fjeansilva** [caljp13/QD-Infinity-Scroll#8]
Verifiquei que não consigo manter o history da páginação,  após acessar os detalhes de um determinado produto, quando retorno (botão voltar), o infinity-Scroll executa novamente indo para o topo e voltando com a páginação 0. Tem algum parâmetro ou função para que possa manter esse histórico da pesquisa?

**Comment by caljp13** [comment]
@fjeansilva o Infinity Scroll não possui suporte nativo a histórico de navegação, porém se você fizer uma customização é possível integra-lo ao seu script através dos métodos de callbacks e paginação.
