### ISSUE TITLE
Estou tendo problemas com o Paginate

### ISSUE THREAD

**Issue by guihgs** [caljp13/QD-Infinity-Scroll#9]
Consegui fazer uma parte do script para carregar usando um button mas a parte que n encontrei na documentação é de definir o limite de produtos quando acabar os produtos rodar a condicional para remover o botão e adicionar uma mensagem 

          paginate: function(nextPage) {
        $(".categoria-load-more").click(function() {
            if(nextPage()){
                $(this).addClass('removeBtn');
                $(this).show();
            return false;
          }
            else{
               $(".categoria-load-more").hide();
               $(".searchResultsTime").append('<span>Você visualizou todos os produtos!</span>');
            }
        });
    },

**Comment by cvscarlos** [comment]
@guihgs tente isso:
```js
$(window).on("QuatroDigital.is_noMoreResults", function() {
	console.log('Não existem mais produtos para serem exibidos!');
});
```

**Comment by guihgs** [comment]
Muito obrigado funcionou perfeitamente
